openergate/core/urls.py
from django.conf.urls import url
from core.views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_role', add_role),
    url(r'^edit_role$', edit_role),
    url(r'^role_list$', role_list),
    url(r'^ajax_role$', ajax_role),
]

openergate/openergate/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls')),
    url(r'^', include('core.urls')),
    url(r'^workflow/', include('workflow.urls', namespace='workflow')),
]

openergate/workflow/urls.py
from django.conf.urls import url
from workflow.views import *


urlpatterns = [
    url(r'^$', link_task, name='link_task'),
    url(r'^add_order/$', add_order, name='add_order'),
    url(r'^edit_order/$', edit_order, name='edit_order'),
    url(r'^ajax_order$', ajax_order, name='ajax_order'),
    url(r'^order_list/$', order_list, name='order_list'),
    url(r'^supervisor_task/$', supervisor_task, name='supervisor_task'),
    url(r'^waiting_task/$', waiting_task, name='waiting_task'),
    url(r'^sent_task/$', sent_task, name='sent_task'),
    url(r'^done_task/$', done_task, name='done_task'),
    url(r'^del_task/$', del_task, name='del_task'),
    url(r'^link_task/$', link_task, name='link_task'),
    url(r'^all_task/$', all_task, name='all_task'),
    url(r'^unlock_task/$', unlock_task, name='unlock_task'),
    url(r'^ajax_task$', ajax_task, name='ajax_task'),
    url(r'^add_task/$', add_task, name='add_task'),
    url(r'^show_task$', show_task, name='show_task'),
    url(r'^edit_task$', edit_task, name='edit_task'),
    url(r'^get_task_info$', get_task_info, name='get_task_info'),
    url(r'^ajax_get_log$', ajax_get_log, name='ajax_get_log'),    

#------------申请类型---------------
]

openergate/workflow/models.py
from django.db import models

# Create your models here.
class Work_order(models.Model):
    '''工单表'''
    name = models.CharField('工单名(英文)',max_length=30,unique=True)
    title = models.CharField('标题',max_length=30)
    desc = models.TextField('描述', blank=True)
    flow = models.CharField('流程',max_length=10,blank=True)
    take_time = models.IntegerField('操作需要时间',default=1, blank=True)
    is_active = models.IntegerField('是否启用',default=1)
    creator = models.CharField('创建人',max_length=30)
    create_time = models.DateTimeField('创建时间',auto_now_add=True)
    update_time = models.DateTimeField('更新时间',auto_now=True)

class Task(models.Model):
    '''任务表'''
    title = models.CharField('标题',max_length=30)
    creator = models.CharField('创建人',max_length=30)
    work_order_id = models.IntegerField('工单id')
    flow = models.CharField('流程',max_length=10,blank=True)
    data = models.CharField('表单提交数据',max_length=999)
    state = models.IntegerField('当前状态',default=1)
    cur_role_id = models.IntegerField('当前处理角色id')
    cur_users = models.CharField('当前可处理人列表',max_length=999,blank=True)
    cur_user = models.CharField('当前处理人',max_length=30, blank=True)
    create_time = models.DateTimeField('创建时间',auto_now_add=True)
    update_time = models.DateTimeField('更新时间',auto_now=True)

class Task_log(models.Model):
    task_id = models.IntegerField('任务id')
    username = models.CharField('用户名',max_length=30)
    role_id = models.IntegerField('角色id')
    act_type = models.IntegerField('处理类型', default=1)
    act_opinion = models.TextField('处理意见反馈', blank=True,max_length=1000)
    create_time = models.DateTimeField('记录时间',auto_now_add=True) 

openergate/workflow/views.py
#coding:utf-8
import os
import re
import json
import logging
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.contrib.auth.models import User
from django.template.defaulttags import register
from django.contrib.auth.decorators import login_required
from django.conf import settings
from core.models import *
from openergate.comm import *
from core.views import *
from .tasks import exec_task
from .models import *

logger = logging.getLogger(__name__)

@register.filter
def get_flow_names(flow):
    flow_names = '免审批'
    flow_id_list = flow.split('-')
    if flow_id_list[0]:
        flow_name_list = [Role.objects.get(id=role_id).zh_name for role_id in flow_id_list]
        flow_names = '->'.join(flow_name_list)
    return flow_names

@login_required
@require_role(role_list=['workflow_admin'])
def order_list(request):
    title = '工作流列表'
    username = request.user.username
    key = request.GET.get('key','').strip()
    if key:
        rets = Work_order.objects.filter(Q(name__contains=key)|Q(title__contains=key)|Q(desc__contains=key)|Q(creator__contains=key))
    else:
        rets = Work_order.objects.order_by('-id')
    msgnum = rets.count()
    pagenum = settings.PAGE_LIMIT
    return render_to_response('workflow/order_list.html',locals())


@login_required
@require_role(role_list=['workflow_admin'])
def add_order(request):
    title = '添加工作流'
    username = request.user.username
    roles = Role.objects.all()
    return render_to_response('workflow/add_order.html',locals())

@login_required
@require_role(role_list=['workflow_admin'])
def edit_order(request):
    title = '编辑工作流'
    username = request.user.username
    roles = Role.objects.all()
    id = request.GET.get('id','').strip()
    if not id: return HttpResponse('参数错误')
    try:
        ret = Work_order.objects.get(id=int(id))
    except:
        return HttpResponse('id不存在')
    if ret.flow:
        role_ids = [int(row) for row in ret.flow.split('-')]
    else:
        role_ids = []
    return render_to_response('workflow/edit_order.html',locals())

@login_required
@require_role(role_list=['workflow_admin'])
def ajax_order(request):
    username = request.user.username
    if request.method == 'POST':
        result = False
        act = request.POST.get('act','').strip()
        if act == 'add':
            name = request.POST.get('name','').strip()
            if Work_order.objects.filter(name=name): return HttpResponse('工单名已存在')
            title = request.POST.get('title','').strip()
            desc = request.POST.get('desc','')
            is_active = int(request.POST.get('is_active',''))
            flow = request.POST.get('flow','')
            ret = Work_order.objects.create(name=name, title=title, desc=desc, flow=flow, creator=username, is_active=is_active)
            if ret:
                result = '添加成功'
                templates_dir = "%s/templates/workflow" % settings.BASE_DIR
                scripts_dir = "%s/workflow/scripts" % settings.BASE_DIR
                os.system("cd %s;test -f custom/%s_form.html || \cp demo_form.html custom/%s_form.html" % (templates_dir, name, name))
                os.system("cd %s;test -f %s.sh || \cp demo.sh %s.sh" % (scripts_dir, name, name))
        elif act == 'edit':
            name = request.POST.get('name','').strip()
            title = request.POST.get('title','').strip()
            desc = request.POST.get('desc','')
            is_active = int(request.POST.get('is_active',''))
            flow = request.POST.get('flow','')
            ret = Work_order.objects.filter(name=name).update(title=title, desc=desc, flow=flow, creator=username, is_active=is_active)
            if ret: result = '修改成功'
        elif act == 'del':
            id = request.POST.get('id','').strip()
            order_obj = Work_order.objects.filter(id=id)
            ret = order_obj.delete()
            if ret: result = '删除成功'
    return HttpResponse(result)    

@login_required
def link_task(request):
    title = '事项列表'
    username = request.user.username
    rets = Work_order.objects.filter(is_active=1)
    return render_to_response('workflow/link_task.html',locals())

@login_required
@require_role(role_list=['workflow_supervisor'])
def supervisor_task(request):
    title = '督办事项'
    username = request.user.username
    orders = Work_order.objects.all()
    key = request.GET.get('key','').strip()
    if key:
        rets = Task.objects.filter(Q(state=2)|Q(state=3),Q(title__contains=key)|Q(creator__contains=key)|Q(data__contains=key)).order_by('-id')
    else:
        rets = Task.objects.filter(Q(state=2)|Q(state=3)).order_by('-id')
    msgnum = rets.count()
    pagenum = settings.PAGE_LIMIT
    role_dict = get_role_name()
    state_dict = settings.TASK_STATE_DICT
    return render_to_response('workflow/supervisor_task.html',locals())

@login_required
def waiting_task(request):
    title = '待办事项'
    username = request.user.username
    orders = Work_order.objects.all()
    key = request.GET.get('key','').strip()
    if key:
        rets = Task.objects.filter((Q(cur_users__contains=username+';')|Q(cur_user=username)),Q(title__contains=key)|Q(creator__contains=key)|Q(data__contains=key)).order_by('-id')
    else:
        rets = Task.objects.filter(Q(cur_users__contains=username+';')|Q(cur_user=username)).order_by('-id')
    msgnum = rets.count()
    pagenum = settings.PAGE_LIMIT
    print (pagenum)
    role_dict = get_role_name()
    state_dict = settings.TASK_STATE_DICT
    return render_to_response('workflow/waiting_task.html',locals())

@login_required
def sent_task(request):
    title = '已发事项'
    username = request.user.username
    orders = Work_order.objects.all()
    key = request.GET.get('key','').strip()
    if key:
        rets = Task.objects.filter(Q(creator=username),Q(title__contains=key)|Q(creator__contains=key)|Q(data__contains=key)).order_by('-id')
    else:
        rets = Task.objects.filter(creator=username).order_by('-id')
    msgnum = rets.count()
    pagenum = settings.PAGE_LIMIT
    role_dict = get_role_name()
    state_dict = settings.TASK_STATE_DICT
    return render_to_response('workflow/sent_task.html',locals())

@login_required
@require_role(role_list=['workflow_supervisor'])
def all_task(request):
    title = '所有事项'
    username = request.user.username
    orders = Work_order.objects.all()
    key = request.GET.get('key','').strip()
    if key:
        rets = Task.objects.filter(Q(title__contains=key)|Q(creator__contains=key)|Q(data__contains=key)).order_by('-id')
    else:
        rets = Task.objects.order_by('-id')
    msgnum = rets.count()
    pagenum = settings.PAGE_LIMIT
    role_dict = get_role_name()
    state_dict = settings.TASK_STATE_DICT
    return render_to_response('workflow/all_task.html',locals())

@login_required
def done_task(request):
    title = '已办事项'
    username = request.user.username
    orders = Work_order.objects.all()
    rets = Task_log.objects.filter(username=username)
    task_id_list = [ row.task_id for row in rets]
    task_id_list = list(set(task_id_list))
    key = request.GET.get('key','').strip()
    if key:
        rets = Task.objects.filter(~Q(creator=username),Q(id__in=task_id_list),Q(title__contains=key)|Q(creator__contains=key)|Q(data__contains=key)).order_by('-id')
    else:
        rets = Task.objects.filter(~Q(creator=username),Q(id__in=task_id_list)).order_by('-id')
    msgnum = rets.count()
    pagenum = settings.PAGE_LIMIT
    role_dict = get_role_name()
    state_dict = settings.TASK_STATE_DICT
    return render_to_response('workflow/done_task.html',locals())

def get_task_info(request):
    """获取任务信息"""
    id = request.GET.get('id','').strip()
    datas = {}
    if id:
        try:
            ret = Task.objects.get(id=int(id))
            datas['creator'] = ret.creator
            datas['data'] = json.loads(ret.data)
        except:
            pass
    return HttpResponse(json.dumps(datas))

@login_required
def del_task(request):
    """申请人在已发事项列表中撤销工单 申请人在待办事项列表中回退修改的工单可撤销工单"""
    id = request.GET.get('id','').strip()
    if not id: return HttpResponse('参数错误')
    username = request.user.username
    id = int(id)
    ret = Task.objects.get(id=id)
    creator = ret.creator
    cur_user = ret.cur_user
    cur_state = ret.state
    #申请人提交后未被第一个审批角色处理之前还能撤销
    if creator == username and cur_state <= 2:
        cur_role_id = -1
        cur_users = cur_user = act_opinion = ''
        state = role_id = act_type = 0 
        Task.objects.filter(id=id).update(state=state, cur_role_id=cur_role_id, cur_users=cur_users, cur_user=cur_user)
        Task_log.objects.create(task_id=id,username=username,role_id=role_id,act_type=act_type,act_opinion=act_opinion)
        result = '已撤销'
    #审批人已经审批后申请人不能主动撤销，只能由审批人撤销
    elif creator == username and cur_state > 2:
        result = '已进入处理流程，不能撤销，请联系当前处理人进行撤销'
    else:
        result = '您无权撤销'
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
@require_role(role_list=['workflow_supervisor'])
def unlock_task(request):
    """督办人解除锁定审批人"""
    username = request.user.username
    id = request.GET.get('id','').strip()
    if id:
        id = int(id)
        try:
            ret = Task.objects.get(id=id)
            cur_user = ret.cur_user
            Task.objects.filter(id=id).update(cur_user='')
        except:
            return HttpResponse('id不存在')
    else:
        return HttpResponse('数错误')
    return HttpResponseRedirect('/workflow/supervisor_task/')

@login_required
def ajax_task(request):
    user = request.user
    print (user)
    username = user.username
    print (username)
    is_supervisor = 0
    print (is_supervisor)
    #判断是否有督办权限
    roles = [row.name for row in user.role_set.all()]
    if 'workflow_supervisor' in roles: 
        is_supervisor = 1
        print (is_supervisor)
        admin_role_id = Role.objects.get(name='workflow_supervisor').id
    if request.method == 'POST':

openergate/templates/workflow/add_order.html
{% include 'head.html' %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{{title}}</title>
<link href="/static/workflow/static/css/style.css" rel="stylesheet" type="text/css">
<link href="/static/workflow/static/multiple-select/multiple-select.css" rel="stylesheet">
<script src="/static/workflow/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/workflow/static/multiple-select/jquery.multiple.select.js"></script>
<script src="/static/workflow/static/js/admin.js" type="text/javascript"></script>
</head>
<body>
<script type="text/javascript">
$(document).ready(function() {
    $("#addTable").click(function(){
       var tr="<tr><td align=\"left\" valign=\"middle\"><select name=\"act_type\" id=\"act_type\" class=\"form_2 w300\"><option value='' selected=\"selected\">请选择角色</option>{% for role in roles %}<option value={{ role.id }}>{{ role.zh_name }}</option>{% endfor %}</select></td></tr>"
　  　$("#table").append(tr);
    });

    $("#deleteTable").click(function(){
        document.getElementById('table').deleteRow(-1);
    });

    $('#name').change(function(){
        var name = $(this).val();
        if(/[\u4E00-\u9FA5]/g.test(name)){ 
            alert("工单名不能存在汉字");
            $(this).val('');
            return False;
        }
    });

    $('#submit').click(function(){
        var act = $("#act").val();
        var name = $("#name").val();
        var title = $("#title").val();
        var desc = $("#desc").val();
        var is_active = $("input[name='is_active']:checked").val();
        var flow = [];
        $('table select').each(function(){
            flow.push($(this).val()); 
        });
        var flow = flow.join("-");
        $.post("{% url 'workflow:ajax_order' %}", {"act":act, "name":name, "title":title, "desc":desc, "is_active":is_active, "flow":flow}, function(json){ 
            alert(json);
            window.close();
            window.parent.opener.location.reload();
        });
    });
});
</script>
<div class="adminTable">
<div class="infoForm">
<h3>{{title}}</h3>
<input id="act" name="act" type="hidden" value="add">
<label class="control-label">工单名(英文)</label>
<input id="name" type="text" class="form_2" placeholder='cicd'><br><br>
<label class="control-label">标题</label>
<input id="title" type="text" class="form_2" placeholder='申请CICD发布权限'><br><br>
<label class="control-label">描述</label>
<input id="desc" type="text" class="form_2" placeholder='申请CICD发布权限'><br><br>
<label class="control-label">是否激活</label>
<label> <input type="radio" name="is_active" checked="checked" value="1">激活 </label>
<label> <input type="radio" name="is_active" value="0">禁用</label><br><br>
<input id="addTable" type="submit" value="添加审批流程" class="Btn" />
<input id="deleteTable" type="submit" value="删除审批流程" class="Btn" /><br><br>
<table id="table" border="0" cellspacing="0" cellpadding="0">
<thead>
</thead> 
<tbody> 
{% for role_id in role_ids %}
  <tr>
    <td align="left" valign="middle">
        <select class="form_2 w300">
            <option value='' selected="selected">请选择角色</option>
            {% for role in roles %}
            <option value={{ role.id }}>{{ role.zh_name }}</option>
            {% endfor %}
        </select>
    </td>
  </tr>
{% endfor %}
</tbody> 
</table><br>
<input id="submit" type="submit" value="提交" class="btn btn-round btn-success" />
</div>
<br>
创建工作流说明：(以创建申请CICD发布权限工作流为例)<br>
1.提交创建工作流表单，系统会自动创建工单模板和处理脚本;<br>
2.修改工单表单模板 mysite/templates/workflow/cicd_form.html;<br>
3.修改工作流视图文件，表单数据定义 workflow/views.py;<br>
4.编写工单处理脚本 workflow/scripts/cicd.sh;<br>
</div>
</body>
</html>

openergate/templates/workflow/add_task.html
{% include 'head.html' %}
<script type="text/javascript">
$(document).ready(function() {
    $('#submit').click(function(){
        if($("#next_user").length>0){
            var next_user = $("#next_user").children('option:selected').val();
            if(next_user==''){
                alert('请选择审批人');
                return false;
            }
        }
        /*var message = check_submit();
        if(message) {
            alert(message);
            return false;
        }*/
        if(confirm("确认提交吗？")){ 
            $.post("{% url 'workflow:ajax_task' %}", $("form").serialize(), function(json){ 
                alert(json);
		window.location = document.referrer;
            });
	    return false;
        }
        return false;
    });
});
</script>
<div id="wizard" class="form_wizard wizard_horizontal">
                      <ul class="wizard_steps anchor">
                        <li>
                          <a href="#step-1" class="done" isdone="1" rel="1">
                            <span class="step_no">1</span>
                            <span class="step_descr">
                                              第一步<br>
                                              <small>填写表单</small>
                                          </span>
                          </a>
                        </li>
                        <li>
                          <a href="#step-2" class="disabled" isdone="0" rel="2">
                            <span class="step_no">2</span>
                            <span class="step_descr">
                                              第二步<br>
                                              <small>等待审批</small>
                                          </span>
                          </a>
                        </li>
                        <li>
                          <a href="#step-3" class="disabled" isdone="0" rel="3">
                            <span class="step_no">3</span>
                            <span class="step_descr">
                                              第三步<br>
                                              <small>审批完成</small>
                                          </span>
                          </a>
                        </li>
                      </ul>
                      </div><div id="step-2" class="content" style="display: none;">
                      </div><div id="step-3" class="content" style="display: none;">
</div>
<div class="ln_solid"></div>
<div class="adminTable">
<div class="infoForm">
<h3>申请人信息</h3>
<label class="control-label" for="inputEmail">姓名</label>
<input id="creator_name" name="creator_name" type="text" class="form_2 searchIpnutBtn" value="{{ user.last_name }}" readonly="true">
<label class="control-label" for="inputEmail">邮箱</label>
<input id="creator_mail" name="creator_mail" type="text" class="form_2 searchIpnutBtn" value="{{ user.email }}" readonly="true">
<form id="infoForm">
<input id="act" name="act" type="hidden" class="form_2 searchIpnutBtn" value="add">
<input id="next_role_id" name="next_role_id" type="hidden" class="form_2 searchIpnutBtn" value={{ next_role_id }}>
<input id="creator" name="creator" type="hidden" class="form_2 searchIpnutBtn" value="{{ creator }}">
<input id="task_id" name="task_id" type="hidden" class="form_2 searchIpnutBtn" value="{{ task_id }}">
<input id="work_order_id" name="work_order_id" type="hidden" class="form_2 searchIpnutBtn" value={{ work_order_id }}>
</div>
</div>
{% include template_name %}  
</form>
<div class="adminTable">
<div class="infoForm">
<h3>流程</h3>
START->{{work_order_flow|get_flow_names}}->{{ role_dict.0 }}->END
</div>
</div>
<div class="adminTable">
<div class="infoForm">
<h3>处理人意见</h3>
{% for row in task_log %}
<label class="control-label" for="inputEmail">{{ row.create_time}}  {{ role_dict|get_item:row.role_id }}:{{ row.username }}({{ act_type_dict|get_item:row.act_type }})</label><br>
<label class="control-label" for="inputEmail">{{ row.act_opinion }}</label><br><br>
{% endfor %}
</div>
</div>
{% include 'tail.html' %}

openergate/templates/workflow/link_task.html
{% include 'head.html' %}
<script type="text/javascript">
$(document).ready(function() {

});
</script>
<div class="adminTable">
<div class="infoForm">
<section class="content-header">
</section>
{% for ret in rets %}
<a href="javascript:void(0);" class="btn btn-round btn-success" onclick="openWin('{% url 'workflow:add_task' %}?order_id={{ ret.id}}');">{{ ret.title }}{% if not ret.flow %}(免审批){% endif %}</a>
{% endfor %}
</div>
</div>
{% include 'tail.html' %}

openergate/templates/workflow/sent_task.html
{% include 'head.html' %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
<link href="/static/css/style.css" rel="stylesheet" type="text/css">
<link href="/static/multiple-select/multiple-select.css" rel="stylesheet">
<script src="/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/multiple-select/jquery.multiple.select.js"></script>
<script src="/static/js/admin.js" type="text/javascript"></script>
</head>
<body>
<script type="text/javascript">
window.parent.$("#sent_num").html({{msgnum}});
function change_info(){
        var args = $("#key").serialize();
        window.location = window.location.pathname + "?" + args;
    }
$(document).ready(function() {
$("#key").keydown(function(e){
    if(e.keyCode==13){
        change_info()
    }
});
});
</script>
<div class="adminTable">
<table width="100%"  cellspacing="0" cellpadding="0" class="table table-striped">
<thead>
  <tr>
    <th align="left" valign="middle">id</th>
    <th align="left" valign="middle">工单名</th>
    <th align="left" valign="middle">申请人</th>
    <th align="left" valign="middle">申请时间</th>
    <th align="left" valign="middle">更新时间</th>
    <th align="left" valign="middle">当前处理角色</th>
    <th align="left" valign="middle">当前处理人列表</th>
    <th align="left" valign="middle">当前锁定者</th>
    <th align="left" valign="middle">流程状态</th>
    <th align="center" valign="middle">操作</th>
  </tr>
</thead>
<tbody>
{% load pagination_tags %}
{% autopaginate rets pagenum %}
{% for ret in rets %}
  <tr id={{ret.id}}>
    <td align="left" valign="middle">{{ret.id}}</td>
    <td align="left" valign="middle">{{ret.title}}</td>
    <td align="left" valign="middle">{{ret.creator}}</td>
    <td align="left" valign="middle">{{ret.create_time|date:"Y-m-d H:i:s"}}</td>
    <td align="left" valign="middle">{{ ret.update_time|date:"Y-m-d H:i:s" }}</td>
    <td align="left" valign="middle">{{role_dict|get_item:ret.cur_role_id}}</td>
    <td align="left" valign="middle">{{ ret.cur_users }}</td>
    <td align="left" valign="middle">{{ ret.cur_user }}</td>
    <td align="left" valign="middle">{{ state_dict|get_item:ret.state }}</td>
    <td align="center" valign="middle"><a href="javascript:void(0);" class="fa fa-eye" onclick="openWin('{% url 'workflow:show_task' %}?id={{ ret.id}}');"></a> {% ifequal ret.state 1 %}<a href="javascript:void(0);" class="fa fa-edit" onclick="openWin('{% url 'workflow:add_task' %}?id={{ ret.id}}');"></a>{% endifequal %} {% ifequal ret.state 4 %}<a href="javascript:void(0);" class="fa fa-edit" onclick="openWin('{% url 'workflow:edit_task' %}?id={{ ret.id}}');"></a>{% endifequal %} {% ifequal ret.state 2 %}<a href="{% url 'workflow:del_task' %}?id={{ ret.id }}" class="fa fa-mail-reply"></a>{% endifequal %}</td>
  </tr>
{% endfor %}
</tbody>
</table>
{% paginate %}
</div>
</body>
</html>

{% include 'tail.html' %}

openergate/templates/workflow/supervisor_task.html
{% include 'head.html' %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
<link href="/static/css/style.css" rel="stylesheet" type="text/css">
<link href="/static/multiple-select/multiple-select.css" rel="stylesheet">
<script src="/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/multiple-select/jquery.multiple.select.js"></script>
<script src="/static/js/admin.js" type="text/javascript"></script>
</head>
<body>
<script type="text/javascript">
window.parent.$("#supervisor_num").html({{msgnum}});
function change_info(){
        var args = $("#key").serialize();
        window.location = window.location.pathname + "?" + args;
    }
$(document).ready(function() {
$("#key").keydown(function(e){
    if(e.keyCode==13){
        change_info()
    }
});
});
</script>
<div class="adminTable">
<table width="100%"  cellspacing="0" cellpadding="0" class="table table-striped">
<thead>
  <tr>
    <th align="left" valign="middle">id</th>
    <th align="left" valign="middle">工单名</th>
    <th align="left" valign="middle">申请人</th>
    <th align="left" valign="middle">申请时间</th>
    <th align="left" valign="middle">更新时间</th>
    <th align="left" valign="middle">当前处理角色</th>
    <th align="left" valign="middle">当前处理人列表</th>
    <th align="left" valign="middle">当前锁定者</th>
    <th align="left" valign="middle">流程状态</th>
    <th align="center" valign="middle">操作</th>
  </tr>
</thead>
<tbody>
{% load pagination_tags %}
{% autopaginate rets pagenum %}
{% for ret in rets %}
  <tr id={{ret.id}}>
    <td align="left" valign="middle">{{ret.id}}</td>
    <td align="left" valign="middle">{{ret.title}}</td>
    <td align="left" valign="middle">{{ret.creator}}</td>
    <td align="left" valign="middle">{{ret.create_time|date:"Y-m-d H:i:s"}}</td>
    <!--<td align="left" valign="middle">{{ret.create_time|date:"Y-m-d H:i:s"}}</td>-->
    <td align="left" valign="middle">{{ ret.update_time|date:"Y-m-d H:i:s" }}</td>
    <td align="left" valign="middle">{{role_dict|get_item:ret.cur_role_id}}</td>
    <td align="left" valign="middle">{{ ret.cur_users }}</td>
    <td align="left" valign="middle">{{ ret.cur_user }}</td>
    <td align="left" valign="middle">{{ state_dict|get_item:ret.state }}</td>
    <td align="center" valign="middle"><a href="javascript:void(0);" class="fa fa-eye" onclick="openWin('{% url 'workflow:show_task' %}?id={{ ret.id}}');"></a> <a href="javascript:void(0);" class="fa fa-edit" onclick="openWin('{% url 'workflow:edit_task' %}?id={{ ret.id}}');"></a> <a href="{% url 'workflow:unlock_task' %}?id={{ ret.id }}" class="fa fa-unlock-alt" ></a></td>
  </tr>
{% endfor %}
</tbody>
</table>
{% paginate %}
</div>
</body>
</html>

{% include 'tail.html' %}